#if !defined(AFX_CLOCK_H__2F6842A6_18DF_4109_8DD4_A70ACB4AB6FA__INCLUDED_)
#define AFX_CLOCK_H__2F6842A6_18DF_4109_8DD4_A70ACB4AB6FA__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CClock wrapper class

class CClock : public CWnd
{
protected:
	DECLARE_DYNCREATE(CClock)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x762d73ca, 0xb8, 0x4f74, { 0x89, 0x1, 0xa6, 0x4, 0xdc, 0xd3, 0x5f, 0xbe } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	OLE_COLOR GetBackColor();
	void SetBackColor(OLE_COLOR);
	OLE_COLOR GetForeColor();
	void SetForeColor(OLE_COLOR);
	short GetInterval();
	void SetInterval(short);

// Operations
public:
	void Hello();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CLOCK_H__2F6842A6_18DF_4109_8DD4_A70ACB4AB6FA__INCLUDED_)
